### ISSUE TITLE
healthcheck not working

### ISSUE THREAD

**Issue by xmlking** [bufbuild/bufstream-demo#21]
healthcheck is not working. does it has the `nc` binary? 

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/2ee36bd8-10f2-43d0-b5b2-d112869ad39a">

```sh
      - "9092:9092"
    healthcheck:
      test: nc -z bufstream 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
```
I needed working healthcheck for `bufstream` to use along with `Redpanda Console`

trying it here: https://github.com/xmlking/arroyo-experiments

**Comment by xmlking** [comment]
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/58620c11-71a4-4fe5-9fb2-3b6b6e6546b8">

**Comment by pkwarren** [comment]
Thank you for the report - should be fixed now.
